#!/usr/bin/env bash

build() {
  rm -rf target
  cargo build
  cargo build --release
}
[[ $1 = 'b' ]] && build

# show size of builds
du -sh target/*/gitnu

rust_files() {
  git ls-files | grep rs$
}

lines_in_file() {
  let lines=0
  while read -r i; do
    [[ $i != '' ]] && let lines++
  done <$1
  echo $lines
}

summarize() {
  printf "\nSUMMARY\n"
  let total=0
  while read -r file; do
    lines=$(lines_in_file $file)
    let total+=$lines
    printf -v padded "% 4d" $lines
    echo "$padded | $file"
  done < <(rust_files)
  printf "\n$total lines total\n\n"
}

summarize
