#!/usr/bin/env bash

build() {
  rm -rf target
  cargo build
  cargo build --release
}

[[ $1 = 'b' ]] && build

du -sh target/*/gitnu

let lines=0

files() {
  git ls-files | grep rs$ | grep -v test
}

while read -r i; do
  [[ $i != '' ]] && let lines++
done < <(files | xargs cat)

echo "$lines lines of rust code"

count_lines() {
  let ll=0
  while read -r i; do
    [[ $i != '' ]] && let ll++
  done < <(cat $1)
  echo $ll
}

while read -r i; do
  ll=$(count_lines $i)
  printf -v padded "% 4d" $ll
  echo "$padded | $i"
done < <(files)

scc src/*.rs
