#!/usr/bin/env bash

# final result
# this allows all tests to run even if some fail in-between
EXITCODE=0

# run unit tests
RUST_BACKTRACE=1 cargo test || EXITCODE=1

# run integration tests
bash tests/run $@ || EXITCODE=1

exit $EXITCODE
