#!/usr/bin/env node

const fs = require('fs')
const { exec } = require('child_process')
const process = require('process')

function timed(command) {
  for (let i = 0; i < 1000; i++) {
    exec(command)
  }
}

process.chdir('repo/some/thing')
const startTime = performance.now()
timed('../../dist/cgit')
const endTime = performance.now()
const result = endTime - startTime
console.debug('Elapsed time:', result)

const content = result.toString() + '\n'

fs.writeFileSync('time.txt', content, (err) => {
  if (err) {
    console.error(err)
  }
})
