#[derive(Debug, PartialEq)]
pub enum GitCommand {
    // full list found from running `git help --all`
    Add,
    Am,
    Annotate,
    Apply,
    Archimport,
    Archive,
    Attributes,
    Bisect,
    Blame,
    Branch,
    Bugreport,
    Bundle,
    CatFile,
    CheckAttr,
    CheckIgnore,
    CheckMailmap,
    CheckRefFormat,
    Checkout,
    CheckoutIndex,
    Cherry,
    CherryPick,
    Citool,
    Clean,
    Cli,
    Clone,
    Column,
    Commit,
    CommitGraph,
    CommitTree,
    Config,
    CountObjects,
    Credential,
    CredentialCache,
    CredentialStore,
    Cvsexportcommit,
    Cvsimport,
    Cvsserver,
    Daemon,
    Describe,
    Diagnose,
    Diff,
    DiffFiles,
    DiffIndex,
    DiffTree,
    Difftool,
    FastExport,
    FastImport,
    Fetch,
    FetchPack,
    FilterBranch,
    FmtMergeMsg,
    ForEachRef,
    ForEachRepo,
    FormatBundle,
    FormatChunk,
    FormatCommitGraph,
    FormatIndex,
    FormatPack,
    FormatPatch,
    FormatSignature,
    Fsck,
    Gc,
    GetTarCommitId,
    Gitk,
    Gitweb,
    Grep,
    Gui,
    HashObject,
    Help,
    Hook,
    Hooks,
    HttpBackend,
    Ignore,
    ImapSend,
    IndexPack,
    Init,
    Instaweb,
    InterpretTrailers,
    Log,
    LsFiles,
    LsRemote,
    LsTree,
    Mailinfo,
    Mailmap,
    Mailsplit,
    Maintenance,
    Merge,
    MergeBase,
    MergeFile,
    MergeIndex,
    MergeOneFile,
    MergeTree,
    Mergetool,
    Mktag,
    Mktree,
    Modules,
    MultiPackIndex,
    Mv,
    NameRev,
    Notes,
    P4,
    PackObjects,
    PackRedundant,
    PackRefs,
    PatchId,
    ProtocolCapabilities,
    ProtocolCommon,
    ProtocolHttp,
    ProtocolPack,
    ProtocolV2,
    Prune,
    PrunePacked,
    Pull,
    Push,
    Quiltimport,
    RangeDiff,
    ReadTree,
    Rebase,
    Reflog,
    Remote,
    Repack,
    Replace,
    RepositoryLayout,
    RequestPull,
    Rerere,
    Reset,
    Restore,
    RevList,
    RevParse,
    Revert,
    Revisions,
    Rm,
    Scalar,
    SendEmail,
    SendPack,
    ShI18n,
    ShSetup,
    Shortlog,
    Show,
    ShowBranch,
    ShowIndex,
    ShowRef,
    SparseCheckout,
    Stash,
    Status(bool),
    Stripspace,
    Submodule,
    Svn,
    Switch,
    SymbolicRef,
    Tag,
    UnpackFile,
    UnpackObjects,
    UpdateIndex,
    UpdateRef,
    UpdateServerInfo,
    Var,
    VerifyCommit,
    VerifyPack,
    VerifyTag,
    Version,
    WhatChanged,
    Worktree,
    WriteTree,
}

impl GitCommand {
    fn skip_next_arg(&self, arg: &str) -> bool {
        use GitCommand as G;
        match (self, arg) {
            (G::Log, "-n") => true,
            _ => false,
        }
    }
}

impl TryFrom<&str> for GitCommand {
    type Error = ();
    fn try_from(arg: &str) -> Result<Self, ()> {
        use GitCommand::*;
        match arg {
            "add" => Ok(Add),
            "am" => Ok(Am),
            "annotate" => Ok(Annotate),
            "apply" => Ok(Apply),
            "archimport" => Ok(Archimport),
            "archive" => Ok(Archive),
            "attributes" => Ok(Attributes),
            "bisect" => Ok(Bisect),
            "blame" => Ok(Blame),
            "branch" => Ok(Branch),
            "bugreport" => Ok(Bugreport),
            "bundle" => Ok(Bundle),
            "cat-file" => Ok(CatFile),
            "check-attr" => Ok(CheckAttr),
            "check-ignore" => Ok(CheckIgnore),
            "check-mailmap" => Ok(CheckMailmap),
            "check-ref-format" => Ok(CheckRefFormat),
            "checkout" => Ok(Checkout),
            "checkout-index" => Ok(CheckoutIndex),
            "cherry" => Ok(Cherry),
            "cherry-pick" => Ok(CherryPick),
            "citool" => Ok(Citool),
            "clean" => Ok(Clean),
            "cli" => Ok(Cli),
            "clone" => Ok(Clone),
            "column" => Ok(Column),
            "commit" => Ok(Commit),
            "commit-graph" => Ok(CommitGraph),
            "commit-tree" => Ok(CommitTree),
            "config" => Ok(Config),
            "count-objects" => Ok(CountObjects),
            "credential" => Ok(Credential),
            "credential-cache" => Ok(CredentialCache),
            "credential-store" => Ok(CredentialStore),
            "cvsexportcommit" => Ok(Cvsexportcommit),
            "cvsimport" => Ok(Cvsimport),
            "cvsserver" => Ok(Cvsserver),
            "daemon" => Ok(Daemon),
            "describe" => Ok(Describe),
            "diagnose" => Ok(Diagnose),
            "diff" => Ok(Diff),
            "diff-files" => Ok(DiffFiles),
            "diff-index" => Ok(DiffIndex),
            "diff-tree" => Ok(DiffTree),
            "difftool" => Ok(Difftool),
            "fast-export" => Ok(FastExport),
            "fast-import" => Ok(FastImport),
            "fetch" => Ok(Fetch),
            "fetch-pack" => Ok(FetchPack),
            "filter-branch" => Ok(FilterBranch),
            "fmt-merge-msg" => Ok(FmtMergeMsg),
            "for-each-ref" => Ok(ForEachRef),
            "for-each-repo" => Ok(ForEachRepo),
            "format-bundle" => Ok(FormatBundle),
            "format-chunk" => Ok(FormatChunk),
            "format-commit-graph" => Ok(FormatCommitGraph),
            "format-index" => Ok(FormatIndex),
            "format-pack" => Ok(FormatPack),
            "format-patch" => Ok(FormatPatch),
            "format-signature" => Ok(FormatSignature),
            "fsck" => Ok(Fsck),
            "gc" => Ok(Gc),
            "get-tar-commit-id" => Ok(GetTarCommitId),
            "gitk" => Ok(Gitk),
            "gitweb" => Ok(Gitweb),
            "grep" => Ok(Grep),
            "gui" => Ok(Gui),
            "hash-object" => Ok(HashObject),
            "help" => Ok(Help),
            "hook" => Ok(Hook),
            "hooks" => Ok(Hooks),
            "http-backend" => Ok(HttpBackend),
            "ignore" => Ok(Ignore),
            "imap-send" => Ok(ImapSend),
            "index-pack" => Ok(IndexPack),
            "init" => Ok(Init),
            "instaweb" => Ok(Instaweb),
            "interpret-trailers" => Ok(InterpretTrailers),
            "log" => Ok(Log),
            "ls-files" => Ok(LsFiles),
            "ls-remote" => Ok(LsRemote),
            "ls-tree" => Ok(LsTree),
            "mailinfo" => Ok(Mailinfo),
            "mailmap" => Ok(Mailmap),
            "mailsplit" => Ok(Mailsplit),
            "maintenance" => Ok(Maintenance),
            "merge" => Ok(Merge),
            "merge-base" => Ok(MergeBase),
            "merge-file" => Ok(MergeFile),
            "merge-index" => Ok(MergeIndex),
            "merge-one-file" => Ok(MergeOneFile),
            "merge-tree" => Ok(MergeTree),
            "mergetool" => Ok(Mergetool),
            "mktag" => Ok(Mktag),
            "mktree" => Ok(Mktree),
            "modules" => Ok(Modules),
            "multi-pack-index" => Ok(MultiPackIndex),
            "mv" => Ok(Mv),
            "name-rev" => Ok(NameRev),
            "notes" => Ok(Notes),
            "p4" => Ok(P4),
            "pack-objects" => Ok(PackObjects),
            "pack-redundant" => Ok(PackRedundant),
            "pack-refs" => Ok(PackRefs),
            "patch-id" => Ok(PatchId),
            "protocol-capabilities" => Ok(ProtocolCapabilities),
            "protocol-common" => Ok(ProtocolCommon),
            "protocol-http" => Ok(ProtocolHttp),
            "protocol-pack" => Ok(ProtocolPack),
            "protocol-v2" => Ok(ProtocolV2),
            "prune" => Ok(Prune),
            "prune-packed" => Ok(PrunePacked),
            "pull" => Ok(Pull),
            "push" => Ok(Push),
            "quiltimport" => Ok(Quiltimport),
            "range-diff" => Ok(RangeDiff),
            "read-tree" => Ok(ReadTree),
            "rebase" => Ok(Rebase),
            "reflog" => Ok(Reflog),
            "remote" => Ok(Remote),
            "repack" => Ok(Repack),
            "replace" => Ok(Replace),
            "repository-layout" => Ok(RepositoryLayout),
            "request-pull" => Ok(RequestPull),
            "rerere" => Ok(Rerere),
            "reset" => Ok(Reset),
            "restore" => Ok(Restore),
            "rev-list" => Ok(RevList),
            "rev-parse" => Ok(RevParse),
            "revert" => Ok(Revert),
            "revisions" => Ok(Revisions),
            "rm" => Ok(Rm),
            "scalar" => Ok(Scalar),
            "send-email" => Ok(SendEmail),
            "send-pack" => Ok(SendPack),
            "sh-i18n" => Ok(ShI18n),
            "sh-setup" => Ok(ShSetup),
            "shortlog" => Ok(Shortlog),
            "show" => Ok(Show),
            "show-branch" => Ok(ShowBranch),
            "show-index" => Ok(ShowIndex),
            "show-ref" => Ok(ShowRef),
            "sparse-checkout" => Ok(SparseCheckout),
            "stash" => Ok(Stash),
            "status" => Ok(Status(true)),
            "stripspace" => Ok(Stripspace),
            "submodule" => Ok(Submodule),
            "svn" => Ok(Svn),
            "switch" => Ok(Switch),
            "symbolic-ref" => Ok(SymbolicRef),
            "tag" => Ok(Tag),
            "unpack-file" => Ok(UnpackFile),
            "unpack-objects" => Ok(UnpackObjects),
            "update-index" => Ok(UpdateIndex),
            "update-ref" => Ok(UpdateRef),
            "update-server-info" => Ok(UpdateServerInfo),
            "var" => Ok(Var),
            "verify-commit" => Ok(VerifyCommit),
            "verify-pack" => Ok(VerifyPack),
            "verify-tag" => Ok(VerifyTag),
            "version" => Ok(Version),
            "whatchanged" => Ok(WhatChanged),
            "worktree" => Ok(Worktree),
            "write-tree" => Ok(WriteTree),
            _ => Err(()),
        }
    }
}
