#!/usr/bin/env python3

import subprocess
import pprint
import json
import sys
from data_structure import *
from git_utils import keyphrases
from shell import system

pp = pprint.PrettyPrinter(indent=4).pprint


class bcolors:
    HEADER = "\033[95m"
    OKBLUE = "\033[94m"
    OKCYAN = "\033[96m"
    OKGREEN = "\033[92m"
    WARNING = "\033[93m"
    FAIL = "\033[91m"
    ENDC = "\033[0m"
    BOLD = "\033[1m"
    UNDERLINE = "\033[4m"


ansi = ["\x1b[32m", "\x1b[31m", "\x1b[m"]


def print_and_extract_git_status(checkpoints: list[str]):
    result = []
    process = subprocess.Popen(
        ["git", "-c", "status.color=always", "status"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )
    if not process.stdout:
        return
    index = 1
    started = False
    while process.stdout.readable():
        line = process.stdout.readline()
        if not line:
            break
        stripped = line.strip()
        for i in ansi:
            stripped = stripped.replace(i, "")
        result.append((index, stripped))
        if started:
            if stripped in checkpoints:
                print(line, end="")
                continue
            else:
                print(index, line, end="")
                index += 1
        else:
            if stripped in checkpoints:
                started = True
            print(line, end="")
    return result



def get_cache_filepath() -> str:
    cache_directory = system(["git", "rev-parse", "--git-dir"])
    return "%s/gitn.json" % (cache_directory)


def update_cache(cache_filepath: str, table: dict):
    with open(cache_filepath, "w") as f:
        json.dump(table, f)


# print and extract git status
# enumerate git status
# update cache
def gitn_status():
    git_status = print_and_extract_git_status(keyphrases.set_state_keys)
    if not git_status:
        return
    table = create_table(git_status)
    update_cache(get_cache_filepath(), table)


# read from existing cache (do a full git bypass if there's no cache)
def gitn_add(args):
    # handles ranges in gitn add
    # gitn add 2-5 === gitn add 2 3 4 5
    add_range, rm_range = [], []
    for arg in args:
        if "-" in arg:
            try:
                split = list(map(int, arg.split("-")))
            except:
                continue
            if len(split) != 2 and not all(isinstance(x, int) for x in split):
                continue
            rm_range.append(arg)
            add_range.extend(map(str, range(split[0], split[1] + 1)))
    for i in rm_range:
        args.remove(i)
    args.extend(add_range)
    # read existing cache
    git_command = ["git", "add", "--"]
    table = {}
    try:
        with open(get_cache_filepath(), "r") as f:
            table = json.load(f)
        add_list = list(
            map(lambda x: get_filename(table.get(x, make_empty_entry())), args)
        )
        git_command.extend(add_list)
    except:
        git_command.extend(args)
    git_command = list(filter(None, git_command))
    subprocess.run(git_command)


def handle_arguments(args: list[str]):
    num_args = len(args)
    if num_args <= 1:
        gitn_status()
        return
    # from here on there are at least two args
    command, trailing = args[1], args[2:]
    if command == "status":
        gitn_status()
    if command == "add":
        if len(trailing) == 0:
            print("Nothing specified, nothing added.")
            return
        gitn_add(trailing)
    # print("command:", command)
    # print("trailing:", trailing)


def main():
    handle_arguments(sys.argv)


if __name__ == "__main__":
    main()
